#!/usr/bin/env ruby

require "overcover"

if ARGV[0]
  f = ARGV[0]
  if f == 'on_hook'
    sample = (ARGV[1] == '--sample')
    Overcover::GitReporter.on_hook(sample)
  elsif f =~ /_spec.rb/
    Overcover::Reporter.analyse_spec(f)
  else
    Overcover::Reporter.analyse_file(f)
  end
else
  Overcover::Reporter.summarize
end
